### ISSUE TITLE
OpenADx - News

### ISSUE THREAD

**Issue by ariexi** [EclipseFdn/openadx.eclipse.org#10]
Do you think, the press release as well as the project review for Eclipse Cloe will fit for the News section?

Link to Press Release (currently in draft state): https://docs.google.com/document/d/18v3e7FMTs_ojJb-ih7wbQt3cL9MavcsBU0ZMsD712yA/edit?ts=5cffc7bd[](https://docs.google.com/document/d/18v3e7FMTs_ojJb-ih7wbQt3cL9MavcsBU0ZMsD712yA/edit?ts=5cffc7bd)

Link to Cloe project proposal: [https://projects.eclipse.org/proposals/eclipse-cloe](https://projects.eclipse.org/proposals/eclipse-cloe)

**Comment by ericpoirier** [comment]
Yes they both can go under the News section.

Just provide me the following information for both News items:

Title
Short description
Full description (if internal page)
Link (if external page)


Thanks.

**Comment by ariexi** [comment]
**Title** 
OpenADx Becomes Eclipse Working Group - Focused on Interoperability in the Autonomous Driving Software Stack

**Short description**
The Eclipse Foundation today announced the launch of the OpenADx Working Group, an automotive industry collaboration focused on creating better compatibility, interfaces, and broader interoperability for the autonomous driving development stack.

**Link (will be external then)**
[Link to (Draft) Press Release](https://docs.google.com/document/d/18v3e7FMTs_ojJb-ih7wbQt3cL9MavcsBU0ZMsD712yA/edit?ts=5cffc7bd)

**Comment by ariexi** [comment]
**Title**
First OpenADx project - Eclipse Cloe - in community review now

**Short description**
The first open source project which will be contributed by the OpenADx Eclipse Working Group is now in the community review.

_What is Eclipse Cloe?_
Eclipse Cloe is an enhanced middleware solution for closed-loop simulations, with a focus on functional software tests on system level. Cloe is used as a development tool for interactive and scripted workstation simulations, for code debugging, and for automated tests on servers. Cloe covers a central part of the verification and validation strategy, needed by all vendors in the field of Automated Driving.

[Learn more here...](https://projects.eclipse.org/proposals/eclipse-cloe)

**Link**
[Link to Eclipse Cloe Project](https://projects.eclipse.org/proposals/eclipse-cloe)

**Comment by ericpoirier** [comment]
> **Title**
> OpenADx Becomes Eclipse Working Group - Focused on Interoperability in the Autonomous Driving Software Stack
> 
> **Short description**
> The Eclipse Foundation today announced the launch of the OpenADx Working Group, an automotive industry collaboration focused on creating better compatibility, interfaces, and broader interoperability for the autonomous driving development stack.
> 
> **Link (will be external then)**
> [Link to (Draft) Press Release](https://docs.google.com/document/d/18v3e7FMTs_ojJb-ih7wbQt3cL9MavcsBU0ZMsD712yA/edit?ts=5cffc7bd)

Please provide the link of the Press Release when it is ready.

Thanks.

**Comment by ariexi** [comment]
> 
> 
> > **Title**
> > OpenADx Becomes Eclipse Working Group - Focused on Interoperability in the Autonomous Driving Software Stack
> > **Short description**
> > The Eclipse Foundation today announced the launch of the OpenADx Working Group, an automotive industry collaboration focused on creating better compatibility, interfaces, and broader interoperability for the autonomous driving development stack.
> > **Link (will be external then)**
> > [Link to (Draft) Press Release](https://docs.google.com/document/d/18v3e7FMTs_ojJb-ih7wbQt3cL9MavcsBU0ZMsD712yA/edit?ts=5cffc7bd)
> 
> Please provide the link of the Press Release when it is ready.
> 
> Thanks.

Of course, I will do that!

**Comment by ericpoirier** [comment]
Hi Andy,

Do we still need to link the news item to the press release?

Thanks.

**Comment by ariexi** [comment]
Hi Eric,
Press Release will be finalized in the next days, maybe today.
I guess, we can remove the link for now. 
When the PR is ready, we can do a separate post?
What do you think?
Best,
Andy

**Comment by ericpoirier** [comment]
Ok I will remove the news item the should have linked to the press release and when the PR is ready I will create a new News item for that.

Let me know when the PR is ready.

Thanks.

**Comment by ariexi** [comment]
Of course!
Thank you so much!

**Comment by ariexi** [comment]
I know, I am a bit late, but I have following News:

26th August 2019:
Welcome EclipseSource Munich GmbH in the OpenADx Working Group.

27th August 2019: 
Press Release
OpenADx Becomes Eclipse Working Group Focused on Interoperability in the Autonomous Driving Software Stack
(see also: https://www.globenewswire.com/news-release/2019/08/27/1906959/0/en/OpenADx-Becomes-Eclipse-Working-Group-Focused-on-Interoperability-in-the-Autonomous-Driving-Software-Stack.html)

10th September 2019:
OpenADx at the Mocrosft booth on IAA

**Comment by chrisguindon** [comment]
I believe these request were done via https://github.com/EclipseFdn/openadx.eclipse.org/pull/38

If not, please open a new issue!

Thanks @burcakkalmuk
