### ISSUE TITLE
OpenADx - Projects

### ISSUE THREAD

**Issue by ariexi** [EclipseFdn/openadx.eclipse.org#11]
Currently, we have one project, Eclipse Cloe
[Here is the link to the project proposal](https://projects.eclipse.org/proposals/eclipse-cloe)

We have to figure out, how other working groups will be connected, e.g. openMobility, openPASS, ...

**Comment by ericpoirier** [comment]
Since Eclipse Cloe is still in the proposal phase, should we wait until creating the Projects page on OpenADx? Or should we highlight on the projects page that this is a project proposal for now?

**Comment by ariexi** [comment]
Hopefully, Cloe reach the "creation review" state soon ...
Wayne wrote me, that approval is needed from Executive director and he was out-of-office last week.
Maybe today ...
We are working internally on the necessary steps for an initial contribution.

**Comment by ariexi** [comment]
My proposal is to highlight it on the project page as a project proposal for now.

**Comment by ericpoirier** [comment]
Ok no problem, I will highlight this as a project proposal.

**Comment by ericpoirier** [comment]
The projects page was created and contains the proposal of the project Cloe.

Please reopen this issue if there are changes to be made to the Projects page.

Thanks.
