### ISSUE TITLE
Update OpenADX Manifesto on Resources page

### ISSUE THREAD

**Issue by jph152** [EclipseFdn/openadx.eclipse.org#122]
We have a new version of the "OpenADX Manifesto" whitepaper, featuring updated membership titles. 

Please replace the existing version on https://openadx.eclipse.org/resources/ with the following:
[OpenADx-Manifesto-v07-2020.pdf](https://github.com/EclipseFdn/openadx.eclipse.org/files/5661957/OpenADx-Manifesto-v07-2020.pdf)

**Comment by ariexi** [comment]
@jph152, compared with the former version of the Manifesto, it looks like that format has been broken ...
Font looks different and some superscript numbers has bigger size ...
Could you please have a look on that?

Thanks!

**Comment by jph152** [comment]
@ariexi We were able to find a font that is close to the original since we don't have access to the font used here (Cabin). Please let me know if the attached PDF works for you.
[OpenADx-Manifesto-v12-2020.pdf](https://github.com/EclipseFdn/openadx.eclipse.org/files/5668712/OpenADx-Manifesto-v12-2020.pdf)

**Comment by ariexi** [comment]
@jph152 I added the changes to PR #121 
It is in the queue for release now ... ;-)

**Comment by jph152** [comment]
Thanks!
