### ISSUE TITLE
Add ARM Limited as User Member on OpenADx website

### ISSUE THREAD

**Issue by ZahraFazli** [EclipseFdn/openadx.eclipse.org#125]
Hello, 
Please add ARM Limited as a User Member on the OpenADx working group https://openadx.eclipse.org/members/

![ARM](https://user-images.githubusercontent.com/50374570/101828990-5494aa80-3b00-11eb-8212-e01ad5196811.png)

Thank you!

**Comment by flora8984461** [comment]
Hello @ZahraFazli ,
Please check the preview: https://deploy-preview-126--eclipsefdn-openadx.netlify.app/members/

Do you want to put any descriptions? 

Thanks!

**Comment by flora8984461** [comment]
Sorry @ZahraFazli , I just noticed that there is already a PR from https://github.com/EclipseFdn/openadx.eclipse.org/pull/124, and he has included a description for ARM, I have included it as well. 

Thanks!
