### ISSUE TITLE
Add Link(s) to "Building Safe Algorithms in the Open"

### ISSUE THREAD

**Issue by ariexi** [EclipseFdn/openadx.eclipse.org#136]
There is a real good blog post series from our iceoryx partner and Eclipse Member Apex.AI

**Comment by autumnfound** [comment]
Whats the link to the content, and where would you like the link? We can add it to our queue of things to update this week!

**Comment by ariexi** [comment]
@autumnfound, wow, great!! That was a really fast response!

Here are the links:
1. https://www.apex.ai/post/building-safe-algorithms-in-the-open-part-1-design
2. https://www.apex.ai/post/building-safe-algorithms-in-the-open-part-2-implementation
3. https://www.apex.ai/post/building-safe-algorithms-in-the-open-part-3-integration

I would like to have them on page: https://openadx.eclipse.org/resources/ -> chapter "HowTos"

If possible, could you please also add following paper in the same section as a download like the whitepaper?
https://drive.google.com/file/d/1NFnnKXjvtYWFVYDS03pWg-Cs-C_kb_MN/view

I have the permission from Dejan to publish the presentation. I can forward, if you like.

Thank you so much!

Best,
Andy

**Comment by ariexi** [comment]
[-Shared-_How Apex.AI Certified ROS 2 According to ISO 26262 ASIL-D (AWF TSC April 2021).pdf](https://github.com/EclipseFdn/openadx.eclipse.org/files/6403214/-Shared-_How.Apex.AI.Certified.ROS.2.According.to.ISO.26262.ASIL-D.AWF.TSC.April.2021.pdf)

**Comment by linkfang** [comment]
Hi @ariexi, 
3 links and the paper download were added, here is the preview link:
https://deploy-preview-137--eclipsefdn-openadx.netlify.app/

Thanks!

**Comment by ariexi** [comment]
Thank you @linkfang, looks great!
