### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ariexi** [EclipseFdn/openadx.eclipse.org#25]
Within the OpenADx steering committee we found some people who could also do the web page content.
Is it possible to connect you with them that they can get an introduction to "Hugo"?

Thx.

Best,
Andy

**Comment by ariexi** [comment]
Any news on this?
Thanks!
Best,
Andy

**Comment by chrisguindon** [comment]
Hi @ariexi,

I would be happy to offer some group training! Feel free to reach out to me via email to set this up!
