### ISSUE TITLE
Add "Eclipse iceoryx" project to "Projects"

### ISSUE THREAD

**Issue by ariexi** [EclipseFdn/openadx.eclipse.org#26]
Could you please add the project "Eclipse iceoryx" to the project section?

Content:
Eclipse iceoryx is a middleware with a zero-copy shared memory approach which is optimized for the huge data inter-process-communication. 

URL:
https://projects.eclipse.org/projects/technology.iceoryx

Thx!

Best,
Andy

**Comment by ericpoirier** [comment]
Hi Andy,

This project has been added to the production website.
