### ISSUE TITLE
OpenADx - Events

### ISSUE THREAD

**Issue by ariexi** [EclipseFdn/openadx.eclipse.org#3]
Out first event will be our founding workshop on 25th June.
Could you please refer to the url [https://openadx-workshop.eventbrite.com](https://openadx-workshop.eventbrite.com) ?

Event - OpenADx Workshop - Forming an Eclipse Working Group 
Date: 25th June 2019
Location: Filderhalle Leinfelden-Echterdingen (near Stuttgart airport)

We are happy to invite you to our first meeting about forming the Eclipse OpenADx Working Group.

This event will bring all interested parties together for information about the Eclipse Working Group idea. 
**Everyone is invited!** 
We will also discuss technical aspects and continue our open exchange.

Please see the [OpenADx Working Group wiki page](https://wiki.eclipse.org/OpenADx) for more information. 
The meeting is organized by the Eclipse Foundation and Bosch as an Eclipse member, and will be held under the Eclipse Bylaws (Eclipse Bylaws, Industry Working Group Process, Eclipse Intellectual Property Policy, Eclipse Anti-Trust Policy).

Please [register here](https://openadx-workshop.eventbrite.com) for the event! (and don´t forget to add the event to your calendar … ;-) )

Follow us on our [mailing list](https://dev.eclipse.org/mailman/listinfo/openadx)!

**Comment by ericpoirier** [comment]
Hi,

The event was added in a pull request that was committed this week.

Please reopen this issue if there are changes to be made to the event.

Thanks.
