### ISSUE TITLE
OpenADx - Vision

### ISSUE THREAD

**Issue by ariexi** [EclipseFdn/openadx.eclipse.org#4]
Autonomous driving (AD) is an extremely complex challenge with a complex development process, which is slowed at every turn by incompatibility between widely used development tools. The tools we already use in and of themselves are very good, but they do not work seamlessly with one another simply because they were never designed to work with each other.
This is an industry-wide issue.  It slows us all down in the race to automated driving. It costs money and precious resources to reduce the problem to a manageable level. And the thing about it is that the tool chain itself is not something we can monetize.

All major stakeholders/users have issues associated with tool incompatibility, data conversion and lost time.

We lessen this problem by creating the leading automated driving ecosystem ➢ OpenADx
We leverage open collaboration and open source to:
- Accelerate time to market
- Increase efficiency
- Focus on customers

It is the goal of this working group to deliver
- An industry-wide accepted definition of the AD toolchain
- A reference architecture defining the interoperability of interesting in scope technologies
- Open Source projects for better interoperability and functionality of the established development tools

The working group will:
- Coordinate the development of related Eclipse Foundation projects towards an OpenADx framework.
- Define and manage the specifications for interfaces and functions for the framework.
- Promote the OpenADx framework and its value.
- Provide a vendor neutral marketing and other services to the OpenADx ecosystem.
- Define licensing and intellectual property flows that encourage community participation and tool adoption.
- Drive the funding model that enables this working group and its community to operate on a sustainable basis.

The OpenADx Working Group will deliver software tools and open source software for the development of autonomous driving (AD) by defining open interface specifications for software used in vehicle-based systems and testing environments, where the latter will typically be implemented using cloud services performing software builds, virtual test runs, and collecting results. 
The name OpenADx thus stands for "Open, Autonomous Driving Accelerator". 
The group is formed by multiple parties from around the world and supported by several well-known industry-leading companies. 
-- The OpenADx Working Group is set up as a working group under the governance of the Eclipse Foundation. --

**Comment by ariexi** [comment]
There is very small bug on the web page [https://eclipsefdn.github.io/openadx.eclipse.org/vision/](https://eclipsefdn.github.io/openadx.eclipse.org/vision/)

Could you please insert a line break between "OpenADx" and "We" in the line:
> We lessen this problem by creating the leading automated driving ecosystem ➢ OpenADx We leverage open collaboration and open source to:

It is above the first bullet list.

**Comment by ericpoirier** [comment]
Hi,

A pull request was merged this morning to update this typo.

Please reopen this issue if you'd like to make changes changes to the Vision page.

Thanks.
