### ISSUE TITLE
News on main page

### ISSUE THREAD

**Issue by ariexi** [EclipseFdn/openadx.eclipse.org#46]
There is a difference between the "News" on the News page and on the Main page.
Can we fix this?

Question on that: Do you have to maintain the news on both pages or are there references?
To prevent double work, I would like to think about my page concept, if you have to maintain news on both sites.

Thx!

**Comment by burcakkalmuk** [comment]
No I don't need to maintain both pages. It does automatically. I just realized that I forgot to type in the category information that's why news and events weren't showing up on main page. Sorry! @ariexi

**Comment by ariexi** [comment]
@burcakkalmuk No worries, everything is fine! Thank you so much! Best, Andy
