### ISSUE TITLE
OpenADx - Members

### ISSUE THREAD

**Issue by ariexi** [EclipseFdn/openadx.eclipse.org#5]
First member parties who signed the participation agreement are:
- [itemis](https://www.itemis.com/en/)
- [Eteration A.S.](https://www.eteration.com/)

More will follow ...

**Comment by ericpoirier** [comment]
Should we create a Members page and display only the members logo?

If so, can you provide the companies logo?

Thanks.

**Comment by ariexi** [comment]
Good point.
I guess, I have to ask for permission to use the logo, right?
I will ask...

**Comment by ericpoirier** [comment]
Hi Andy,

Any news about the Members page?

**Comment by ariexi** [comment]
Yes, following are the founding members:
- AVL List GmbH
- Eteration A.S.
- JC Information Management GmbH
- IBM
- itemis AG
- Red Hat
- Robert Bosch GmbH
- Siemens AG

Is it possible to use the logos on the Member page? 
https://www.eclipse.org/membership/exploreMembership.php

I will ask for the logos ...

Thx
Best,
Andy

**Comment by ariexi** [comment]
As I am still not able to attach files, I will provide you the logos via email ...

Best,
Andy

**Comment by ericpoirier** [comment]
> Yes, following are the founding members:
> 
> * AVL List GmbH
> * Eteration A.S.
> * JC Information Management GmbH
> * IBM
> * itemis AG
> * Red Hat
> * Robert Bosch GmbH
> * Siemens AG
> 
> Is it possible to use the logos on the Member page?
> https://www.eclipse.org/membership/exploreMembership.php

Yes we can use logos from the members page.

> 
> I will ask for the logos ...
> 
> Thx
> Best,
> Andy

**Comment by ericpoirier** [comment]
Hi Andy,

Quick question, do you have any participation levels with the members or are they all on the same level of participation?

Thanks.

**Comment by ariexi** [comment]
Hi Eric,

good question…
As I do not know every signed PA and we are in the incubation phase, I guess every founding member is a “participant member” till 30th June 2020.
Starting 01st July 2020, we will have different participation levels …

[cid:image001.png@01D55392.F34FEDD0]


Best,
Andy

Mit freundlichen Grüßen / Best regards

Andreas Riexinger

Chassis Systems Control, Product Management Automated Driving (CC-AD/PRM-P)
Robert Bosch GmbH | Postfach 13 55 | 74003 Heilbronn | GERMANY | www.bosch.com<http://www.bosch.com>
Tel. +49 7062 911-8264 | Mobil +49 172 7258214 | Fax +49 711 811-5111226 | Threema<threema://add/?id=2U9UM5XS> / Threema Work<threemawork://add/?id=2U9UM5XS>: 2U9UM5XS | Andreas.Riexinger@de.bosch.com<mailto:Andreas.Riexinger@de.bosch.com>

Sitz: Stuttgart, Registergericht: Amtsgericht Stuttgart, HRB 14000;
Aufsichtsratsvorsitzender: Franz Fehrenbach; Geschäftsführung: Dr. Volkmar Denner,
Prof. Dr. Stefan Asenkerschbaumer, Dr. Michael Bolle, Dr. Christian Fischer, Dr. Stefan Hartung,
Dr. Markus Heyn, Harald Kröger, Christoph Kübel, Rolf Najork, Uwe Raschke, Peter Tyroller


Von: Eric Poirier <notifications@github.com>
Gesendet: Donnerstag, 15. August 2019 16:29
An: EclipseFdn/openadx.eclipse.org <openadx.eclipse.org@noreply.github.com>
Cc: Riexinger Andreas (CC-AD/PRM-P) <Andreas.Riexinger@de.bosch.com>; Author <author@noreply.github.com>
Betreff: Re: [EclipseFdn/openadx.eclipse.org] OpenADx - Members (#5)


Hi Andy,

Quick question, do you have any participation levels with the members or are they all on the same level of participation?

Thanks.

**Comment by ericpoirier** [comment]
Hi Andy,

The members page is now live on production.

https://openadx.eclipse.org/members/

Please reopen this issue if you'd like to make any changes to that page.

Thanks.

**Comment by ariexi** [comment]
EclipseSource joined the OpenADx Working Group.
Could you please add them on the member page?
Thanks!

**Comment by ariexi** [comment]
EclipseSource joined the OpenADx Working Group.
Could you please add them on the member page?
Thanks!

**Comment by chrisguindon** [comment]
PR #35 from @burcakkalmuk was merged today.

@ariexi In the future, would it be possible to create a new issue instead of re-opening this one? This makes it hard for us to track if there is new things we need to do on the website!

**Comment by ariexi** [comment]
@chrisguindon Sorry, I will do it better next time!

**Comment by chrisguindon** [comment]
@ariexi no worries! Thanks!
