### ISSUE TITLE
News - ADLINK Technology joined OpenADx

### ISSUE THREAD

**Issue by ariexi** [EclipseFdn/openadx.eclipse.org#51]
**Title** ADLINK Technology joined OpenADx
**Full description (if internal page)** ADLINK Technology joined today the OpenADx working group to work with us along the autonomous driving toolchain.
ADLINK created and published the [Eclipse Cyclone DDS project.](https://projects.eclipse.org/projects/iot.cyclonedds)
ADLINK is interested to build together with us a cool middleware based on Eclipse Cyclone DDS and Eclipse iceoryx.
 
**Link (if external page)** [ADLINK Technology](https://www.adlinktech.com/)

**Comment by autumnfound** [comment]
This is live! Thanks @burcakkalmuk!
