### ISSUE TITLE
Members - please add ADLINK Technology

### ISSUE THREAD

**Issue by ariexi** [EclipseFdn/openadx.eclipse.org#52]
Could you please add ADLINK Technology as new member?

Could you please add a little explanation, what ADLINK is about?
(Source is Eclipse member site)

"ADLINK is Leading EDGE COMPUTING by delivering the network nodes that enable practical and scalable IoT systems."

**Comment by autumnfound** [comment]
This is live! Thanks @burcakkalmuk!
