### ISSUE TITLE
New Member - DENSO Corporation

### ISSUE THREAD

**Issue by ariexi** [EclipseFdn/openadx.eclipse.org#58]
Could you please add DENSO Corporation as a new member of the OpenADx Working Group?

Could you please add a little explanation, what ADLINK is about?

DENSO is a leading supplier of advanced automotive technology, systems and components for all the world's major automakers.

(Source: https://www.denso.com/de/de/about-us/at-a-glance/)

**Comment by autumnfound** [comment]
This is live!
