### ISSUE TITLE
News - DENSO Corporation joined OpenADx working group

### ISSUE THREAD

**Issue by ariexi** [EclipseFdn/openadx.eclipse.org#59]
**Title** Welcome DENSO Corporation to OpenADx!
**Full description (if internal page)** DENSO Corporation joined the OpenADx working group to work on solutions for autonomous driving.
**Link (if external page)** [Learn more here about DENSO Corporation ...](https://www.denso.com/global/en/)

**Comment by autumnfound** [comment]
This is live!
