### ISSUE TITLE
OpenADx - Working Group

### ISSUE THREAD

**Issue by ariexi** [EclipseFdn/openadx.eclipse.org#6]
**About**
The OpenADx working group will coordinate the development of Eclipse Foundation projects on the following topics:
- Implementation of interfaces between the development steps
- Implementation of common standards from other working groups (e.g. VDA Leitinitiative)
- Definition of an initial setup for fast implementation
- Ensures interoperability between development stages

> Andy: Please insert here the ToolScheme picture

Projects hosted by the Eclipse Foundation in the context of the OpenADx working group apply the Eclipse development process and best practices of openness, transparency and meritocracy. As such, these projects are open to participation by developers or contributors. They can submit contributions to the project that will be considered for inclusion by the project committers. Committer status is acquired by contributors after election by existing committers as described in the Eclipse Development Process.

**Charter**
[OpenADx Working Group Charter](https://www.eclipse.org/org/workinggroups/openadx_charter.php)

**Join OpenADx**
[OpenADx Working Group Participation Agreement (WPGA)](https://www.eclipse.org/org/workinggroups/wpga/openadx_working_group_participation_agreement.pdf)

**Subscribe OpenADx Mailing List**
[Mailing List](https://dev.eclipse.org/mailman/listinfo/openadx)

**Meeting Minutes**
> Andy: We have no meeting minutes at the moment, we will have it after 25th June.

**Contact**
> Andy: Can we implement here a contact form?

**Comment by ariexi** [comment]
I cannot attach a jpg or png ...
Do you have an idea?

**Comment by ericpoirier** [comment]
Hi,

You can drag and drop image in the comment textarea.

**Comment by ericpoirier** [comment]
Hi Andy,

I'm going to close this issue since the Working Group page is live. I was keeping it open since it seems like you were trying to upload new images.

You can reopen this issue if ever you need to add more images.

Thanks.
