### ISSUE TITLE
Events - Bosch ConnectedWorld 2020

### ISSUE THREAD

**Issue by ariexi** [EclipseFdn/openadx.eclipse.org#60]
**Title:** Bosch ConnectedWorld 2020

**Date:** 19th - 20th February 2020

**Location:** Berlin, Germany

Bosch ConnectedWorld - The leading conference on IoT and digital transformation.
Meet us there at the Eclipse booth!

[Learn more here…](https://bosch-connected-world.com/)

**Comment by autumnfound** [comment]
This event announcement is live
