### ISSUE TITLE
OpenADx - Resources

### ISSUE THREAD

**Issue by ariexi** [EclipseFdn/openadx.eclipse.org#7]
**White Papers**
under construction

**Articles & Videos**
Watch the video on OpenADx here on YouTube: [https://youtu.be/7gHLkSzWNKA](https://youtu.be/7gHLkSzWNKA)

[Blog Post: Autonomous Driving Toolchain](https://blog.bosch-si.com/developer/autonomous-driving-toolchain)
[Blog Post: Autonomous Driving Accelerator OpenADx launched](https://blog.bosch-si.com/developer/autonomous-driving-accelerator-openadx-launched)
[Blog Post: 5 things you should know about OpenADx](https://blog.bosch-si.com/developer/5-things-you-should-know-about-openadx)
[Blog Post: OpenADx reaches next level](https://blog.bosch-si.com/mobility/openadx-initiative-reaches-next-level/)
[Vorteile von Open Source fuer ADAS und autonomes Fahren (only in German available)](https://www.elektroniknet.de/elektronik-automotive/assistenzsysteme/vorteile-von-open-source-fuer-adas-und-autonomes-fahren-154085.html)

[YouTube: OpenADx - Leveraging open collaboration & OS to accelerate Autonomous Driving dev](https://www.youtube.com/watch?v=BHGahCzT4Fw&list=PLy7t4z5SYNaQ82WyePL05PFwqNmfTxhwD&index=16)
[YouTube: OpenADx "Autonomous Driving Simulation" Testbed – hardware in the loop (sponsored by Renesas)](https://www.youtube.com/watch?v=UyxdE-olbHE&index=47&list=PLy7t4z5SYNaQ82WyePL05PFwqNmfTxhwD)

**Toolchain Proposal**
under construction

**Cookbooks**
under construction

**HowTo´s**
under construction

**OpenADx Wiki**
[OpenADx Wiki](https://wiki.eclipse.org/OpenADx)

**Comment by ericpoirier** [comment]
Hi,

This page was implemented in the pull request  that was merged this week.

Please reopen this issue if there are changes to be made to the Resources page.

Thanks.
