### ISSUE TITLE
AD Demonstrator "Larry"

### ISSUE THREAD

**Issue by ariexi** [EclipseFdn/openadx.eclipse.org#70]
**Is your feature request related to a problem? Please describe.**
We would like to promote one of our projects, which is currently not an Eclipse project, but uses our iceoryx technology.

**Describe the solution you'd like**
We would like to have a drop-down menu for the navigation item "Projects".
Therefore, we should have 2 entries in the drop-down menu, the fist one is "Eclipse Projects" and the second one is "Other Projects".

**Describe alternatives you've considered**
Or should we "spilt" the project site in 2 sections? What do you think? @burcakkalmuk @autumnfound 

**Additional context**
Here are some links to get an impression, what we would like to do:
Larry-Docu: [https://gitlab.com/larry.robotics/larry.robotics](https://gitlab.com/larry.robotics/larry.robotics)
How to build my own Larry and to bring it to life: [https://gitlab.com/larry.robotics/larry.robotics](https://gitlab.com/larry.robotics/larry.robotics/-/blob/master/larry-T2-build-instructions.md)
Larry-Services: [https://gitlab.com/el.chris/larry-services/-/blob/master/README.md](https://gitlab.com/el.chris/larry-services/-/blob/master/README.md)
Larry-UI: [https://gitlab.com/el.chris/larry-ui/-/blob/master/README.md](https://gitlab.com/el.chris/larry-ui/-/blob/master/README.md)

Introspection in Rust: [https://github.com/elBoberido/iceray](https://github.com/elBoberido/iceray)
Iceoryx-Rust-Binding: [https://github.com/elBoberido/iceoryx-rs](https://github.com/elBoberido/iceoryx-rs)

**Comment by autumnfound** [comment]
Currently there is something on IoT which might match what you're looking for! We have an [adopters page](https://iot.eclipse.org/adopters/) that shows off people who have adopted technologies from the working group. So all this would require is a new page and a new data file to store the info we would need.

**Comment by ariexi** [comment]
Yes, something like that could be if interest, but we (Larry is built from some colleagues within Bosch, also working on iceoryx) would like to have a kind of "advertising page" too.
Do you have a proposal also for that? 
Maybe a combination of both?
Thx!

**Comment by chrisguindon** [comment]
@ariexi I would recommend reaching out to our sales team for advertisement questions: perri.lavergne@eclipse-foundation.org

In regards to the Other Projects page, I will reach out to Ralph to see what we should do here!

**Comment by ariexi** [comment]
@chrisguindon Thanks for your answer. It is not a really "advertising page" it is more like a homebase for a iceoryx related project...

**Comment by waynebeaton** [comment]
Having a working group website include pointers to products and other open source projects that leverage related Eclipse open source technology is fine. Anything more than that is offside.

It would be inappropriate for the OpenADX working group to provide a landing page (or "homebase") for a project that is not hosted at the Eclipse Foundation.

Note that if Larry is moved to the Eclipse Foundation, the project could create a project-specific website as a home base for the project.

**Comment by ariexi** [comment]
@waynebeaton, I am just discussing with the creator. What do you expect for a project?
I think the complete project creation process, right?
What about with the initial contribution then? Because everything is there at the moment...
Is GitLab approved for use in Eclipse projects?

In other words, what is the leanest way for hosting this project at Eclipse?
Thank you so much!

**Comment by ariexi** [comment]
Set on hold!
