### ISSUE TITLE
Events - separation of upcoming and past events

### ISSUE THREAD

**Issue by ariexi** [EclipseFdn/openadx.eclipse.org#76]
**Is your feature request related to a problem? Please describe.**
**Describe the solution you'd like**
For structuring reasons, is it possible to have separate sections of the events?
Upcoming on top and past events in a separate section?
Or is this not possible due to some automated mechanism?

Thanks!

**Comment by ariexi** [comment]
@burcakkalmuk @chrisguindon 
Could you please have a look on that? Is there a possibility to do that?
Thx!
Best,
Andy

**Comment by chrisguindon** [comment]
@ariexi this is possible!

**Comment by ericpoirier** [comment]
Hi Andy,

I created a PR to update the Events list on the home page and Events page. Also I created a Past Events page.

https://deploy-preview-87--eclipsefdn-openadx.netlify.app/
https://deploy-preview-87--eclipsefdn-openadx.netlify.app/past-events/

Let me know what you think and if you'd like to make more changes.

Thanks!
