### ISSUE TITLE
Resources - add video from presentation

### ISSUE THREAD

**Issue by ariexi** [EclipseFdn/openadx.eclipse.org#79]
Add video: ScaleUp 360° Automotive AI: Autonomous Driving and Open Source: Does it fit?, Robert Bosch GmbH
Link: https://www.youtube.com/embed/GBF1vtbP4O0

**Comment by ariexi** [comment]
@autumnfound @ericpoirier Could you please help me inserting the video linked above?
I am not able to do that in a proper way, that it looks fine at the end.
Thank you so much!
Best,
Andy

**Comment by ericpoirier** [comment]
I believe the video has been added to the website.

Please reopen if we missed something from this issue.

Thanks.
