### ISSUE TITLE
OpenADx - Technologies

### ISSUE THREAD

**Issue by ariexi** [EclipseFdn/openadx.eclipse.org#8]
"About Technologies"

Automated Driving (AD) is clustered into three equally important technology areas:
1. In-vehicle technology
2. Cloud technology (backend)
3. Design, development, test and validation tools (tool chain)

OpenADx is currently focused on the AD tool chain. The goal is to accelerate AD development through open collaboration and open source.
OpenADx' vision is to ensure transparency and make the complex AD tool landscape more easily accessible for enterprise users. 

Challenge
AD is a complex challenge and therefore requires a multifaceted development process incorporating a variety of software tools. The tools the industry currently uses are very good, but they don’t seamlessly work with one another. This is a result of the tools not being designed to work together. This is an industry-wide issue that slows us down in the race to AD development. By pooling resources, we can remove the “friction” between widely used tools. We can create something of use to all of us: open, compatible and accessible. 

> insert picture here (sent by email)

**Problem and benefits for OEMs and Tier1s**

User insight: 
"Developing automated driving functions is extremely complicated and requires the use of many complex software tools which do not work efficiently with one another. What I need is a set of tools which work with each other seamlessly so that my teams can move through the development process more quickly and efficiently."

Benefit: 
The automated driving tool chain allows your team to work together more efficiently with a suite of highly integrated tools by enabling seamless transfer of data and code through each step of the automated driving development process.

**Problem and benefits for tool and technology providers**

User insight: 
"Currently, tools used to create automated driving applications do not work efficiently with one another. If our tool/technology is compatible with other widely used technologies and tools, it will ease the development process for our customers and make our products even more attractive to them."

Benefit: 

The seamless integration of your technology in the automated driving tool chain makes it more attractive to organizations developing automated driving applications by increasing their development efficiency. 

Bullet **Simulation and test**

[Link to Eclipse Cloe Project Proposal](https://projects.eclipse.org/proposals/eclipse-cloe) 
> Cloud be the "Learn more" button

**Cloe Description**
Cloe is an enhanced middleware solution for closed-loop simulations, with a focus on functional software tests on system level. Cloe is used as a development tool for interactive and scripted workstation simulations, for code debugging, and for automated tests on servers. Cloe covers a central part of the verification and validation strategy, needed by all vendors in the field of Automated Driving.
- Cloe acts as closed-loop simulation master and middleware for all involved components, such as simulator engine, vehicle controller, and component models.
- Cloe provides a tool for orchestrating such closed-loop simulations in a variety of environments, e.g. on localhost or in a Kubernetes cluster.
- Cloe provides a lightweight web-based user-interface for visualizing the simulation state.
- Simulations are described through Cloe stack-files for reproducibility.

These core characteristics of Cloe allow it to (partially) fulfil the closed-loop simulation in the V&V strategy. Vehicle controllers and models can be easily integrated with Cloe and immediately have access to multiple simulator engines. Given M simulator engines and N vehicle controllers, Cloe allows the number of integrations to be reduced to M+N, rather than M×N that would otherwise be necessary. Multiple simulator engines are supported, proprietary as well as open source. This allows a user to mix-and-match engines to their system-under-test based on test requirements. Cloe provides generalized interfaces allowing ground truth and key-performance indicator extraction, as well as fault injection.

Orchestration features provided by Cloe allow faster scaling of simulation tests and evaluation. Through containerization and the simulation description files, development artifacts along with their tests can be easily archived and the results quickly reproduced.

**Comment by ericpoirier** [comment]
Not entirely sure what the following  links/paragraphs should look like on the page:

Bullet Simulation and test

Link to Eclipse Cloe Project Proposal

Cloud be the "Learn more" button

**Comment by ariexi** [comment]
Sorry, a typo, not "Cloud" I want to say: 
> Could be the "Learn more" button ...

Let me try this way: 
I had in mind, that starting with the "tool chain " overview, we will made the buttons (sorry, buttons not bullets ;-) ) clickable. 
Remembering Stephanie´s proposal, there is a very good implementation.
At first, I have content for the "button" (or better "technology")
So maybe the site can stay for the moment as it is, but later on we should use the "button" for "Simulation and Test" which can be used as title for the current content (Cloe) or a separate web page.

Hope, this helps. If not, let me know, then let´s make a Skype or a Zoom tomorrow ...

**Comment by ericpoirier** [comment]
By the tool chain, you mean the image with the blue icons?

You can see an example of the technology page here on the staging website:
https://eclipsefdn.github.io/openadx.eclipse.org/technologies/

Also, I don't think we can use the image with blue icons and create links out of it to go to a specific tool page as I don't think it will scale for mobile. Could we just using the icons without the dashed line with arrows? If we were to use only the round icons, it would scale for mobile just fine.

Thanks.

**Comment by ariexi** [comment]
Yes, the image with the blue icons.

Yeas, it is fine for me, if the icons will be not clickable. 
Can we implement the section like in issue #13 with the green icons? 
It looks really cool and it is not necessary to make these icons clickable ... ;-)

We can start with only one, the "Simulation and Test" icon ...

Thanks!

**Comment by ericpoirier** [comment]
Ok no problem, I will add only the "Simulation and Test" icon where the same title is located on the page and I will make the Learn more button go to the Eclipse Cloe page.

**Comment by ericpoirier** [comment]
I merged a pull request to update the Technologies page.

We should see the changes in a few minutes.

Please reopen this issue if there are more changes to be made to that page.

Thanks.
