### ISSUE TITLE
Provide a kind of instructions / howtos

### ISSUE THREAD

**Issue by ariexi** [EclipseFdn/openadx.eclipse.org#83]
Could you please provide me a kind of documentation, how I can embed a video like on the resources site?

That would be really helpful!

Thanks!
Best,
Andy

**Comment by ericpoirier** [comment]
Hi Andy,

To add videos to the OpenADx website you need to edit the following file:
/layouts/shortcodes/resources_video_section.html

Also note that the videos are added through a simple link. For example:
<a class="eclipsefdn-video" href="//www.youtube.com/embed/7gHLkSzWNKA"></a>

Solstice will take care of embedding the video into the page.

For more information about how the embedding Youtube videos works, visit the following page:
https://www.eclipse.org/eclipse.org-common/themes/solstice/docs/index.php#embedding-youtube-videos

Let me know if that helps or if you need more information.

Thanks.

**Comment by ericpoirier** [comment]
Hi Andy,

I'm going to close this issue, please reopen if you need more instructions.

Thanks!
