### ISSUE TITLE
Add OpenADx Manifesto to the "Resources" section

### ISSUE THREAD

**Issue by ChristieWittEclipse** [EclipseFdn/openadx.eclipse.org#94]
Please add the OpenADx Manifesto to [this page](https://openadx.eclipse.org/resources/) by this Thursday July 30th.
I've included the PDF, thumbnail image, and a mockup of what it should look like.

[OpenADx-Manifesto-v07-2020.pdf](https://github.com/EclipseFdn/openadx.eclipse.org/files/4983552/OpenADx-Manifesto-v07-2020.pdf)
![OpenADx-Thumbnail](https://user-images.githubusercontent.com/58480647/88573819-56594800-d00f-11ea-9669-10cbee3ccb83.png)
![OpenADx-Whitepaper-Sample](https://user-images.githubusercontent.com/58480647/88573821-56f1de80-d00f-11ea-91dc-6fe50383627c.jpg)

**Comment by ChristieWittEclipse** [comment]
Please hold on this as we have gotten some content revisions on the Whitepaper.

**Comment by ChristieWittEclipse** [comment]
[OpenADx-Manifesto-v07-2020.pdf](https://github.com/EclipseFdn/openadx.eclipse.org/files/5002614/OpenADx-Manifesto-v07-2020.pdf)
I've attached the final version of the whitepaper. @ariexi is going to publish this himself FYI @chrisguindon @autumnfound

**Comment by chrisguindon** [comment]
@ChristieWittEclipse Thanks for letting us know! I've removed Martin and assigned this issue to @ariexi !

**Comment by ariexi** [comment]
Hi @chrisguindon, Hi @autumnfound, I have a question regarding linking the document...

What I did:
- I added a folder in my Git project `openadx.eclipse.org/resources` and pasted there the document
- I did a reference on the site in this way `href="https://openadx.eclipse.org/resources/OpenADx-Manifesto-v07-2020.pdf"`
But it won´t work. 
What did I wrong?
Thanks!

Best,
Andy

**Comment by ariexi** [comment]
Hi @chrisguindon, Hi @autumnfound, 
ok, I found it, but can you still help me with the alignment, or will this be ok?
What do you think @ChristieWittEclipse ?
Thx!

**Comment by autumnfound** [comment]
The `text-center` class in your shortcode can affect images as well as text. If you remove it or replace it with `text-left`, you should be closer to the desired output!

**Comment by ariexi** [comment]
Thx @autumnfound, but it does not really work ...
https://deploy-preview-100--eclipsefdn-openadx.netlify.app/resources/

**Comment by autumnfound** [comment]
The first thing I notice is that there is a col-sm-offset-6, which means that there's gonna be a bump on tablet size screens and up. The heading underline can be removed to match the mock and it wouldn't look out of place anymore as well.

**Comment by ariexi** [comment]
Thx @autumnfound!

Implemented with #100
